name: untitled
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:
  firebase_core:
  firebase_auth:
  flutter_bloc: ^8.1.4
  fluttertoast: ^8.2.4
  uuid:
  flutter_launcher_icons: ^0.13.1
  firebase_storage:
  image_picker: ^1.0.2

  url_launcher: ^6.1.11
  permission_handler: ^10.0.0


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/image/
